# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the ref you want to point at
    hooks:
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: check-toml
      - id: mixed-line-ending
        args:
          - '--fix=lf'

  - repo: https://github.com/psf/black
    rev: '24.2.0'
    hooks:
      - id: black
        language_version: python3.8
        args:
          - '--line-length=120'

  - repo: https://github.com/pycqa/flake8
    rev: '7.0.0'  # pick a git hash / tag to point to
    hooks:
      - id: flake8
