# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        echo version=$(python -c 'import tomllib                                                                                                                                                            [14:39:48]
          with open("pyproject.toml", "rb") as f:
            print(tomllib.load(f)["project"]["version"])') >> $GITHUB_ENV
    - name: Build package
      run: |
        python -m build
    - name: Upload wheel
      uses: actions/upload-artifact@v3
      with:
        name: "orienter-${{ env.version }}-py3-none-any.whl"
        path: "dist/orienter-${{ env.version }}-py3-none-any.whl"
